# docker-compose.override.yml (temporary for dev)
version: "3.9"

services:
  db:
    image: mariadb:10.9
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"

  wordpress:
    image: clusterstar/project-wordpress-application:latest
    container_name: wp_app
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: secret123
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"

